### ISSUE TITLE
【重要】サイトの閉鎖について

### ISSUE THREAD

**Issue by Meiryo7743** [Meiryo7743/covid-19-ichikawa#260]
- 日本語 -> https://stopcovid19-ichikawa.netlify.app/ja/articles/20210120233106/
- English -> https://stopcovid19-ichikawa.netlify.app/en/articles/20210120233106/

**Comment by Meiryo7743** [comment]
## TODO

- [x] Translate into English
- [x] Create a new branch with the file that states "the website was closed" in multiple languages
- [x] Disable GitHub Actions
- [x] Archive this repository
